#!/bin/sh
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- frankenphp run "$@"
fi

if [ "$1" = "frankenphp" ] && php bin/console --raw | grep -q "^doctrine:migrations:migrate"; then
	php bin/console doctrine:migrations:migrate --allow-no-migration --no-interaction
fi

exec "$@"
